// Narrative generator.
//
// Renders the human-readable engineering exhibit from the structured
// genoa.exhibit.v2 object.  This is intentionally template-based and
// AI-FREE.  An AI assistant may *summarize* this output (and may, in
// the future, draft prose around it) but the source of truth is and
// remains the structured exhibit.  AI MUST NEVER:
//   - calculate contours
//   - change engineering outputs
//   - override warnings
//   - hide uncertainty
//   - fabricate measurements
//   - claim FCC approval

export const CERTIFICATION_LANGUAGE =
  'This exhibit was generated by Genoa FCC Propagation Studio. Deterministic FCC contour calculations are intended for review and certification by a qualified broadcast engineer prior to filing.';

import { guardNarrative } from './guard.js';

export function renderNarrative(exhibit){
  const s   = exhibit.station_inputs || {};
  const m   = exhibit.calculation_method || {};
  const ip  = exhibit.interpolation || {};
  const rt  = exhibit.radial_table || [];
  const fr  = exhibit.filing_readiness || {};
  const ev  = exhibit.evidence || {};
  const pop = exhibit.population_estimate || {};
  const v   = exhibit.validation || {};

  const sections = {
    summary:                  section_summary(exhibit),
    station_inputs:           section_inputs(s),
    fcc_method:               section_method(m, ip),
    contour_results:          section_contour_results(exhibit),
    radial_table:             section_radial_summary(rt, exhibit.contour_definitions || []),
    methodology:              section_methodology(exhibit),
    provenance:               section_provenance(exhibit),
    terrain_evidence:         section_terrain(ev),
    measurement_evidence:     section_measurement(ev),
    county_overlay_evidence:  section_county_overlay(ev),
    conductivity_evidence:    section_conductivity(ev, s),
    am_physics_fccgw_evidence:section_am_physics_fccgw(ev),
    am_physics_evidence:      section_am_physics(ev),
    oet65_evidence:           section_oet65(exhibit),
    identity_evidence:        section_identity(ev),
    validation_evidence:      section_validation(v),
    population:               section_population(pop),
    warnings:                 section_warnings(exhibit.warnings || [], fr),
    source_attestation:       section_source_attestation(exhibit),
    certification:            section_certification(fr)
  };

  const rawText = [
    sections.summary, sections.station_inputs, sections.fcc_method,
    sections.contour_results, sections.radial_table, sections.methodology,
    sections.provenance, sections.terrain_evidence, sections.measurement_evidence,
    sections.county_overlay_evidence, sections.conductivity_evidence,
    sections.am_physics_fccgw_evidence, sections.am_physics_evidence,
    sections.oet65_evidence, sections.identity_evidence,
    sections.validation_evidence, sections.population, sections.warnings,
    sections.source_attestation, sections.certification
  ].join('\n\n');

  // Guard against unsupported engineering claims.  Even though the
  // template author doesn't currently emit forbidden phrasing, this
  // protects future AI-drafted prose from leaking unsupported claims.
  const { text, violations, rewrites } = guardNarrative(rawText, exhibit);

  return {
    text,
    sections,
    certification_language: CERTIFICATION_LANGUAGE,
    ai_used: false,
    guard: { rewrites, violations }
  };
}

function section_provenance(x){
  const fm  = x.facility_metadata || {};
  const ev  = x.evidence || {};
  const v   = x.validation || {};
  const s   = x.station_inputs || {};
  // Two INDEPENDENT validation systems, surfaced separately:
  //   curve_reference_validation — internal golden fixture suite that
  //     pins engine + curve dataset + interpolation.  Drives
  //     CURVE_VALIDATION_MISSING.  This is the authoritative result.
  //   fcc_cross_check — comparison against FCC's published contour at
  //     geo.fcc.gov.  External evidence only.  Drives FCC_GEO_CROSSCHECK_*.
  // Reading v.runs.slice(-1) was always wrong; it grabbed whichever run
  // happened to be appended last (now the FCC cross-check), conflating
  // the two systems.
  const cr = v.curve_reference_validation || null;
  const cc = v.fcc_cross_check || null;
  const lines = [hr('Evidence Provenance')];
  lines.push(`Facility       : ${fm.facility_lookup_source || '—'}${fm.facility_endpoint ? '  · ' + fm.facility_endpoint : ''}`);
  if (fm.facility_updated_at) lines.push(`               (updated ${fm.facility_updated_at})`);
  // Terrain provenance line — labelled "HAAT" for FM/TV (per §73.313),
  // "Ground σ" for AM since §73.183 keys on conductivity, not terrain
  // elevation.  Same evidence packet for AM is the conductivity source.
  const isAmFacility = String(s.service || '').toUpperCase() === 'AM';
  lines.push(isAmFacility
    ? `Ground σ source: ${ev.terrain?.available
        ? `${ev.terrain.source} · ${ev.terrain.method || 'M3'}`
        : 'inputs only (no FCC M3 segmentation attached)'}`
    : `Terrain HAAT   : ${ev.terrain?.available
        ? `${ev.terrain.source} · ${ev.terrain.method} · ${ev.terrain.dem?.source || '—'} ${ev.terrain.dem?.dataset || ''}`
        : 'not attached'}`);
  if (ev.terrain?.endpoint)    lines.push(`               (${ev.terrain.endpoint})`);
  // Curve dataset validation (authoritative — drives CURVE_VALIDATION_MISSING).
  if (cr){
    const crResult =
      cr.result === 'pass'  ? 'PASS — clears CURVE_VALIDATION_MISSING'
    : cr.result === 'fail'  ? `FAIL — engine + dataset drift detected (max err ${cr.max_error_km?.toFixed?.(3) ?? '—'} km vs tolerance ${cr.tolerance_km ?? '—'} km)`
    :                         'NO CASES RUN';
    lines.push(`Curve check    : ${cr.method || 'internal golden fixture suite'} · fixture ${cr.name || '—'}`);
    lines.push(`Curve result   : ${crResult} · ${cr.n_pass ?? 0}/${cr.n_run ?? 0} pass`);
  } else {
    lines.push('Curve check    : no curve-reference run attached');
    lines.push('Curve result   : NO CASES RUN');
  }
  // FCC contour cross-check (evidence-only — drives FCC_GEO_CROSSCHECK_*).
  if (cc){
    const ccResult =
      cc.result === 'pass'    ? 'PASS — engine matches FCC geo contour'
    : cc.result === 'fail'    ? `FAIL — engine differs from FCC contour (max err ${cc.max_error_km?.toFixed?.(2) ?? '—'} km vs tolerance ${cc.tolerance_km ?? '—'} km)`
    : cc.result === 'skipped' ? 'SKIPPED — no usable FCC contour for this station'
    :                           '—';
    lines.push(`FCC cross-chk  : ${cc.method || 'FCC contour cross-check'} · ${cc.source || '—'}`);
    if (cc.endpoint) lines.push(`               (${cc.endpoint})`);
    lines.push(`FCC result     : ${ccResult} · ${cc.n_pass ?? 0}/${cc.n_run ?? 0} pass`);
  } else {
    lines.push('FCC cross-chk  : not attached (ZTR or geo.fcc.gov not reached for this station)');
  }
  lines.push(`Measurements   : ${ev.measurements?.available
    ? `${ev.measurements.source} · ${ev.measurements.n_records} record(s) · calibrated=${!!ev.measurements.calibrated}`
    : 'not attached'}`);
  return lines.join('\n');
}

function section_validation(v){
  // Validation evidence is the curve_reference_validation block.  This
  // is the system that drives CURVE_VALIDATION_MISSING and is therefore
  // the authoritative validation status for filing readiness.  The FCC
  // cross-check is shown separately in section_provenance because it is
  // engineering evidence, not curve-dataset validation.
  const cr = v?.curve_reference_validation || null;
  if (!cr){
    // Legacy fallback for exhibits that still carry only runs[].
    const last = v?.runs?.slice(-1)[0] || null;
    if (!last) return hr('Validation Evidence') + '\nNo validation run attached.';
    return [
      hr('Validation Evidence'),
      `Method      : ${last.method || '—'}`,
      `Source      : ${last.source || '—'}${last.endpoint ? '  (' + last.endpoint + ')' : ''}`,
      `Cases       : ${last.n_pass ?? 0}/${last.n_run ?? 0} pass (authoritative)`,
      `Max error   : ${last.max_error_km != null ? last.max_error_km.toFixed(2) + ' km' : '—'}  · tolerance ${last.tolerance_km ?? '—'} km`,
      `Status      : ${last.authoritative_pass ? 'PASS — clears CURVE_VALIDATION_MISSING' : 'NOT PASSING — CURVE_VALIDATION_MISSING blocker stays'}`
    ].join('\n');
  }
  const status =
    cr.result === 'pass'  ? 'PASS — clears CURVE_VALIDATION_MISSING'
  : cr.result === 'fail'  ? 'FAIL — engine + dataset drift detected; CURVE_VALIDATION_MISSING blocker stays'
  :                         'NO CASES RUN — CURVE_VALIDATION_MISSING blocker stays';
  const lines = [
    hr('Validation Evidence'),
    `Suite       : ${cr.name || '—'} (${cr.method || '—'})`,
    `Fixture     : ${cr.fixture_path || '—'}`,
    `Curve set   : ${cr.curve_dataset?.version || '—'}`,
    `Cases       : ${cr.n_pass ?? 0}/${cr.n_run ?? 0} pass`,
    `Max error   : ${cr.max_error_km != null ? cr.max_error_km.toFixed(3) + ' km' : '—'}  · tolerance ${cr.tolerance_km ?? '—'} km`
  ];
  if (cr.coverage_by_family){
    lines.push('Coverage    :');
    for (const [fam, c] of Object.entries(cr.coverage_by_family)){
      lines.push(`  ${fam.padEnd(16)} ${c.n_pass}/${c.n_run} pass`);
    }
  }
  lines.push(`Ran at      : ${cr.ran_at || '—'}`);
  lines.push(`Status      : ${status}`);

  // Tolerance rationale (brief)
  if (cr.tolerance_rationale?.distance_km){
    lines.push(`Tol basis   : ${cr.tolerance_rationale.distance_km.basis?.[0] || '—'}`);
  }

  // Validation lock statement — machine-readable anchor for FCC review
  const ls = cr.lock_statement || null;
  if (ls){
    lines.push('');
    lines.push('Validation Lock:');
    lines.push(`  Locked at   : ${ls.locked_at || '—'}  (${ls.locked_by || '—'})`);
    lines.push(`  Upstream    : ${ls.upstream_commit || '—'}`);
    lines.push(`  Cases       : ${ls.n_cases ?? cr.n_run ?? 0}`);
    if (ls.families){
      const famSummary = Object.entries(ls.families)
        .map(([k, v]) => `${k} (${v.n_cases})`)
        .join(', ');
      lines.push(`  Families    : ${famSummary}`);
    }
    lines.push(`  Statement   : ${(ls.statement || '').slice(0, 200)}…`);
  }
  return lines.join('\n');
}

const hr = title => `── ${title.toUpperCase()} ${'─'.repeat(Math.max(2, 60 - title.length))}`;

function section_summary(x){
  const s = x.station_inputs || {};
  const fr = x.filing_readiness || {};
  return [
    hr('Engineering Exhibit Summary'),
    `Station ${s.call || '—'} (facility ${s.facility_id || '—'})`,
    `Service: ${s.service || '—'}${s.fcc_class ? ' class ' + s.fcc_class : ''}`,
    `Generated: ${x.generated_at}`,
    `Filing readiness: ${fr.score ?? '—'}/100 — status ${fr.status || '—'}`
  ].join('\n');
}

function section_inputs(s){
  // AM narrative uses §73.183 vocabulary: TPO + ground conductivity +
  // DA/NDA mode.  ERP/HAAT are FM/TV concepts and would look like an
  // FM exhibit imported onto an AM filing — exactly the credibility
  // hit an AM engineer would flag.
  const isAm = String(s.service || '').toUpperCase() === 'AM';
  return [
    hr('Station / Facility Inputs'),
    `Frequency:       ${fmt(s.frequency)} ${s.frequency_unit || ''}`,
    isAm
      ? `TPO:             ${fmt(s.erp_kw)} kW`
      : `ERP (h):         ${fmt(s.erp_kw)} kW`,
    isAm
      ? (Number.isFinite(Number(s.rms_field_1km))
         ? `RMS field @1 km: ${fmt(s.rms_field_1km)} mV/m (filed)`
         : `RMS field @1 km: — (derived from TPO + pattern)`)
      : `HAAT (input):    ${fmt(s.haat_m_input)} m`,
    // AM has no HAAT (groundwave propagation per §73.184 Figure M3 is
    // distance/conductivity/frequency-keyed, not antenna-height-keyed).
    // Render an explicit n/a label so the standard summary keeps the
    // same shape across services; the txt exporter already does this.
    // Tests pin both shape (line present) and content (no metres value).
    isAm ? 'HAAT (input):    n/a (AM)' : null,
    `Coordinates:     ${fmt(s.lat, 5)}, ${fmt(s.lon, 5)}`,
    isAm
      ? `Antenna mode:    ${Array.isArray(s.pattern) ? `DA (${s.pattern.length}-point pattern)` : 'NDA'}`
      : `Pattern:         ${Array.isArray(s.pattern) ? `directional (${s.pattern.length} points)` : 'non-directional'}`,
    `Radial step:     ${s.radial_step_deg}°`,
    isAm ? `Ground σ:        ${fmt(s.ground_sigma_mS_m)} mS/m` : null
  ].filter(Boolean).join('\n');
}

function section_method(m, ip){
  return [
    hr('Applicable FCC Method'),
    `Method:          ${m.name || '—'}`,
    `Regulations:     ${(m.regulations || []).join(', ') || '—'}`,
    `Engine module:   ${m.engine_module || '—'}`,
    `Engine version:  ${m.engine_version || '—'}`,
    `Interpolation:`,
    `  along field:   ${ip?.along_field || '—'}`,
    `  along HAAT:    ${ip?.along_haat  || '—'}`,
    `  source:        ${ip?.source      || '—'}`
  ].join('\n');
}

function section_contour_results(x){
  const polygons = x.polygons || [];
  const lines = [hr('Contour Results')];
  for (const p of polygons){
    const fs = p.field_strength || {};
    lines.push(`${(p.label || p.contour_id).padEnd(36)} mean radial = ${fmt(p.mean_radial_km, 2)} km · area ≈ ${fmt(p.area_km2, 0)} km² (${fs.value ?? '—'} ${fs.unit ?? ''})`);
  }
  if (polygons.length === 0) lines.push('No contour polygons computed (engine returned an empty radial table).');
  return lines.join('\n');
}

function section_radial_summary(rt, contours){
  if (!rt.length) return hr('Radial Table Summary') + '\nradial table is empty.';
  const head = [hr('Radial Table Summary')];
  head.push(`Total radials:      ${rt.length}`);
  if (rt.length){
    const az0  = rt[0].azimuth_deg;
    const azN  = rt[rt.length-1].azimuth_deg;
    head.push(`Azimuth coverage:   ${az0}° … ${azN}°`);
  }
  head.push('Per-contour mean radial:');
  for (const c of contours){
    const ds = rt.map(r => r.contour_distances_km?.[c.id]).filter(Number.isFinite);
    if (!ds.length){ head.push(`  ${c.label.padEnd(34)} —`); continue; }
    const mean = ds.reduce((a,b)=>a+b,0)/ds.length;
    const min  = Math.min(...ds), max = Math.max(...ds);
    head.push(`  ${c.label.padEnd(34)} mean ${fmt(mean,2)} km  min ${fmt(min,2)} max ${fmt(max,2)}`);
  }
  return head.join('\n');
}

function section_methodology(x){
  const mv = x.method_versions || {};
  const sw = x.software_versions || {};
  const cd = mv.curve_dataset || {};
  return [
    hr('Methodology and Reproducibility'),
    `Genoa engine:    ${sw.genoa_engine}`,
    `Schema:          ${sw.schema}`,
    `Node:            ${sw.node}`,
    `Curve dataset:   ${cd.curve_version || '—'}  (meta sha256 ${(cd.meta_sha256 || '').slice(0,12)}…)`,
    `Curve files:`,
    ...Object.entries(cd.dataset_sha256 || {}).map(([k,h]) => `  · ${k.padEnd(18)} sha256 ${h.slice(0,12)}…`),
    `Reproducibility statement:`,
    `  This exhibit is a deterministic function of (station inputs, terrain HAAT per radial,`,
    `  curve dataset version, engine version). Re-running with the same inputs and the same`,
    `  curve dataset version on a different machine MUST produce the same radial table.`
  ].join('\n');
}

function section_terrain(ev){
  if (!ev?.terrain?.available){
    return hr('Supplemental Terrain / ITM Evidence') + '\nNo terrain evidence attached. Engine ran with flat HAAT (or n/a for AM).';
  }
  const t = ev.terrain;
  const lines = [hr('Supplemental Terrain / ITM Evidence')];
  lines.push(`Source:           ${t.source || '—'}`);
  lines.push(`Profiles:         ${t.profiles?.length || 0} radials`);
  return lines.join('\n');
}

function section_measurement(ev){
  if (!ev?.measurements?.available){
    return hr('Measurement Evidence') + '\nNo SDR / SigMF measurement records are attached. Field measurements are evidence, not authority.';
  }
  const m = ev.measurements;
  return [
    hr('Measurement Evidence'),
    `Source:           ${m.source || '—'}`,
    `Records:          ${m.n_records ?? m.records?.length ?? 0}`,
    `Calibrated:       ${m.calibrated ? 'yes' : 'no — measurements reported as raw indications'}`,
    `Author:           ${m.author || '—'}`,
    `Hardware:         ${m.hw || '—'}`
  ].join('\n');
}

function section_population(pop){
  const lines = [hr('Population Estimate')];
  if (pop?.source){
    lines.push(`Persons:          ~${(pop.primary ?? 0).toLocaleString()}`);
    if (pop.protected != null) lines.push(`Protected:        ~${(pop.protected ?? 0).toLocaleString()}`);
    lines.push(`Source:           ${pop.source}`);
    if (pop.dataset)  lines.push(`Dataset:          ${pop.dataset}`);
    if (pop.vintage)  lines.push(`Census vintage:   ${pop.vintage}`);
    if (pop.method)   lines.push(`Method:           ${pop.method}`);
    if (pop.endpoint) lines.push(`Endpoint:         ${pop.endpoint}`);
    if (pop.fetched_at) lines.push(`Fetched at:       ${pop.fetched_at}`);
  } else {
    lines.push(`Primary contour:  ~${(pop?.primary ?? 0).toLocaleString()} (${pop?.model || '—'})`);
    lines.push(`Protected:        ~${(pop?.protected ?? 0).toLocaleString()}`);
    lines.push(`PLACEHOLDER — population sourced from model estimate only.`);
    lines.push(`A Census/ACS dispatch is required for any filing-grade population claim.`);
  }
  return lines.join('\n');
}

function section_warnings(warnings, fr){
  const lines = [hr('Warnings and Limitations')];
  if (!warnings.length) lines.push('No structured warnings raised.');
  for (const w of warnings){
    lines.push(`[${w.severity?.toUpperCase()}] ${w.code}  — ${w.title}`);
    if (w.detail) lines.push(`    ${w.detail}`);
  }
  if (fr?.blockers?.length){
    lines.push('');
    lines.push('Filing-readiness blockers:');
    for (const b of fr.blockers) lines.push(`  · ${b.code} — ${b.detail || b.description || ''}`);
  }
  if (fr?.recommendations?.length){
    lines.push('');
    lines.push('Recommendations:');
    for (const r of fr.recommendations) lines.push(`  · ${r}`);
  }
  return lines.join('\n');
}

function section_certification(fr){
  return [
    hr('Engineering Certification Placeholder'),
    CERTIFICATION_LANGUAGE,
    '',
    `Genoa filing readiness:   ${fr.score ?? '—'}/100  (${fr.status || '—'})`,
    `Engineer of record:       ___________________________`,
    `License #:                ___________________________`,
    `Date:                     ___________________________`,
    `Signature:                ___________________________`
  ].join('\n');
}

function section_county_overlay(ev){
  const co = ev?.county_overlay;
  if (!co){
    return hr('County Boundary Overlay') + '\nNot computed (contour geometry unavailable or AM station without polygon contour).';
  }
  const lines = [hr('County Boundary Overlay')];
  const n = Array.isArray(co.counties_intersected) ? co.counties_intersected.length : '—';
  lines.push(`Counties intersected:  ${n}`);
  if (co.contour_area_sq_km != null) lines.push(`Contour area:          ${fmt(co.contour_area_sq_km, 1)} km²`);

  const fully = Array.isArray(co.counties_fully_contained) ? co.counties_fully_contained : [];
  const partial = Array.isArray(co.counties_partially_intersected) ? co.counties_partially_intersected : [];
  if (fully.length)   lines.push(`Fully contained:       ${fully.length}  (${fully.slice(0,5).join(', ')}${fully.length > 5 ? ', …' : ''})`);
  if (partial.length) lines.push(`Partially intersected: ${partial.length}  (${partial.slice(0,5).join(', ')}${partial.length > 5 ? ', …' : ''})`);

  if (co.warning_code) lines.push(`Warning:               ${co.warning_code}${co.warning_detail ? ' — ' + co.warning_detail : ''}`);

  // List gap counties that were checked via centroid fallback.
  const missing = Array.isArray(co.missing_county_hits) ? co.missing_county_hits : [];
  if (missing.length){
    lines.push('');
    lines.push('FCC endpoint-miss counties (centroid method):');
    for (const m of missing) lines.push(`  · ${m.county || m.key || m}`);
  }

  lines.push('');
  lines.push('Advisory: County boundary data is FCC-derived evidence, not an authoritative service area filing.');
  return lines.join('\n');
}

function section_conductivity(ev, s){
  const gc  = ev?.ground_conductivity;
  const gcr = ev?.ground_conductivity_per_radial;
  const isAm = String(s?.service || '').toUpperCase() === 'AM';

  if (!isAm){
    return hr('Ground Conductivity (M3)') + '\nNot applicable (FM/TV service — §73.183 M3 conductivity lookup is AM-only).';
  }
  if (!gc){
    return hr('Ground Conductivity (M3)') + '\nNo conductivity evidence attached.';
  }

  const lines = [hr('Ground Conductivity (M3)')];
  lines.push(`Available:     ${gc.available ? 'yes' : 'no'}`);
  if (gc.available){
    lines.push(`Source:        ${gc.source || '—'}`);
    lines.push(`σ (mS/m):      ${gc.sigma_mS_m != null ? fmt(gc.sigma_mS_m, 3) : '—'}`);
    if (gc.filing_grade) lines.push(`Filing grade:  ${gc.filing_grade}`);
  } else {
    lines.push(`Reason:        ${gc.reason || '—'}`);
  }

  if (gcr){
    lines.push('');
    if (gcr.available){
      const method = gcr.method || gcr.source || '—';
      const nRadials = Array.isArray(gcr.radials) ? gcr.radials.length : (gcr.n_radials ?? '—');
      lines.push(`Per-radial M3: ${nRadials} radials  ·  method: ${method}`);
      if (gcr.filing_grade) lines.push(`Filing grade:  ${gcr.filing_grade}`);
    } else {
      lines.push(`Per-radial M3: not available — ${gcr.reason || gcr.error || '—'}`);
    }
  }

  lines.push('');
  lines.push('Source: FCC §73.190 Figure M3 (ground conductivity chart) · advisory evidence.');
  return lines.join('\n');
}

function section_am_physics_fccgw(ev){
  const p = ev?.am_physics_fccgw;
  if (!p){
    return hr('AM Physics — FCC/OET R86-1 Ground Wave') + '\nNot computed (FM/TV station or sidecar not configured).';
  }
  const lines = [hr('AM Physics — FCC/OET R86-1 Ground Wave')];
  lines.push(`Status:        ${p.status || '—'}`);
  lines.push(`Engine:        ${p.engine || '—'}`);
  lines.push(`Filing effect: ${p.filing_effect || 'none'} — advisory evidence only`);
  if (p.warning)  lines.push(`Warning:       ${p.warning}`);

  const comps = Array.isArray(p.contour_comparisons) ? p.contour_comparisons : [];
  if (comps.length){
    lines.push('');
    lines.push('FCC curve vs. FCCGW physics comparison:');
    lines.push(`  ${'Level (mV/m)'.padEnd(14)} ${'FCC curve km'.padEnd(14)} ${'FCCGW km'.padEnd(10)} Variance`);
    for (const c of comps){
      const fcc = c.fcc_curve_km != null ? fmt(c.fcc_curve_km, 2) : '—';
      const gw  = c.fccgw_physics_km != null ? fmt(c.fccgw_physics_km, 2) : '—';
      const v   = c.variance_pct != null ? `${fmt(c.variance_pct, 1)}%` : '—';
      lines.push(`  ${String(c.field_mvm).padEnd(14)} ${fcc.padEnd(14)} ${gw.padEnd(10)} ${v}`);
    }
  }

  lines.push('');
  lines.push('Advisory: FCCGW physics cross-check does not modify §73.184 curve-derived contour distances.');
  return lines.join('\n');
}

function section_am_physics(ev){
  const p = ev?.am_physics;
  if (!p){
    return hr('AM Physics — SOMNEC2D Ground-Field Solver') + '\nNot computed (FM/TV station or sidecar not configured).';
  }
  const lines = [hr('AM Physics — SOMNEC2D Ground-Field Solver')];
  lines.push(`Status:        ${p.status || '—'}`);
  lines.push(`Engine:        ${p.engine || '—'}`);
  lines.push(`Filing effect: ${p.filing_effect || 'none'} — advisory evidence only`);
  if (p.warning) lines.push(`Warning:       ${p.warning}`);

  if (p.inputs){
    const inp = p.inputs;
    if (inp.frequency_mhz != null) lines.push(`Frequency:     ${fmt(inp.frequency_mhz, 4)} MHz`);
    if (inp.sigma_ms_m != null)    lines.push(`σ (mS/m):      ${fmt(inp.sigma_ms_m, 3)}  (source: ${inp.sigma_source || '—'})`);
    if (inp.epr != null)           lines.push(`εᵣ:            ${fmt(inp.epr, 1)}  (source: ${inp.epr_source || '—'})`);
  }

  if (p.outputs){
    lines.push('');
    lines.push('Solver outputs:');
    for (const [k, val] of Object.entries(p.outputs)){
      lines.push(`  ${k.padEnd(24)} ${val}`);
    }
  }

  lines.push('');
  lines.push('Advisory: SOMNEC2D is an independent NEC-family ground-field solver. Does not modify §73.184 curve-derived contour distances.');
  return lines.join('\n');
}

function section_oet65(x){
  const o = x?.oet65;
  if (!o){
    return hr('RF Exposure (OET-65 / §1.1310)') + '\nNot computed — OET-65 analysis not attached to this exhibit.';
  }
  const lines = [hr('RF Exposure (OET-65 / §1.1310)')];
  lines.push(`Result:              ${o.pass ? 'PASS' : 'REVIEW REQUIRED'}`);
  lines.push(`Cite:                ${o.cite || '47 CFR §1.1310'}`);
  lines.push(`Bulletin:            ${o.oet65_revision || '—'}`);
  lines.push(`Method:              ${o.method || '—'}`);

  const unc = o.compliance?.uncontrolled;
  const ctl = o.compliance?.controlled;
  if (unc) lines.push(`Uncontrolled dist.:  ${unc.distance_m != null ? fmt(unc.distance_m, 1) + ' m' : '—'}${unc.compliant != null ? '  (' + (unc.compliant ? 'compliant' : 'non-compliant') + ')' : ''}`);
  if (ctl) lines.push(`Controlled dist.:    ${ctl.distance_m != null ? fmt(ctl.distance_m, 1) + ' m' : '—'}${ctl.compliant != null ? '  (' + (ctl.compliant ? 'compliant' : 'non-compliant') + ')' : ''}`);

  const nf = o.near_field;
  if (nf){
    lines.push(`Near-field required: ${nf.required_for_filing ? 'yes' : 'no'}`);
    if (nf.boundary_m != null) lines.push(`Near-field boundary: ${fmt(nf.boundary_m, 1)} m`);
    if (nf.am_screening?.filing_grade){
      lines.push(`AM screening grade:  ${nf.am_screening.filing_grade}`);
    }
  }

  if (o.notes?.length){
    lines.push('');
    for (const n of o.notes) lines.push(`Note: ${n}`);
  }

  lines.push('');
  lines.push('Advisory: OET-65 distances are deterministic rule outputs — review with a qualified engineer before filing.');
  return lines.join('\n');
}

function section_identity(ev){
  const id = ev?.identity;
  if (!id){
    return hr('Station Identity Evidence (EAS / RadioDNS / RDS)') + '\nNo identity evidence attached — identity sidecar not configured or did not respond.';
  }
  const lines = [hr('Station Identity Evidence (EAS / RadioDNS / RDS)')];
  lines.push(`Available:     ${id.available ? 'yes' : 'no'}`);

  if (id.tiers_used?.length) lines.push(`Tiers used:    ${id.tiers_used.join(', ')}`);
  if (id.sources?.length)    lines.push(`Sources:       ${id.sources.join(', ')}`);

  const confirmations = Array.isArray(id.confirmations) ? id.confirmations : [];
  if (confirmations.length){
    lines.push('');
    lines.push('Confirmations:');
    for (const c of confirmations){
      const status = (c.status || '—').toUpperCase();
      const detail = c.value || c.fqdn || c.call || c.detail || '';
      lines.push(`  [${status}] ${(c.kind || '—').padEnd(18)} ${detail}`);
    }
  } else if (id.available){
    lines.push('Confirmations: (none returned)');
  }

  if (!id.available && id.reason) lines.push(`Reason:        ${id.reason}`);

  lines.push('');
  lines.push('Advisory: Identity evidence (EAS, RadioDNS, RDS) is supplemental. FCC call sign authority rests with the FCC license record.');
  return lines.join('\n');
}

function section_source_attestation(exhibit){
  const sa = exhibit.source_attestation;
  if (!sa) return '';

  const hr2 = '─'.repeat(62);
  const lines = [`${hr2}`, 'APPENDIX P — Data Source Provenance', hr2];

  const pct = sa.overall_confidence != null
    ? `${(sa.overall_confidence * 100).toFixed(0)}%`
    : '—';
  lines.push(`Overall source confidence: ${pct}`);
  lines.push('');

  // Per-field table
  const COL = [22, 14, 14, 16, 12];
  const hdr = ['Field', 'Authority', 'Status', 'Confidence', 'Conflict'];
  lines.push(hdr.map((h, i) => h.padEnd(COL[i])).join(''));
  lines.push(COL.map(c => '─'.repeat(c - 1)).join(' '));

  const scores = Array.isArray(sa.field_scores)
    ? sa.field_scores
    : Object.values(sa.fields || {});

  for (const s of scores){
    const row = [
      String(s.field || '').padEnd(COL[0]),
      String(s.source_authority || '').padEnd(COL[1]),
      String(s.verification_status || '').padEnd(COL[2]),
      String(s.confidence != null ? (s.confidence * 100).toFixed(0) + '%' : '—').padEnd(COL[3]),
      String(s.conflict_detail ? 'YES' : '').padEnd(COL[4])
    ];
    lines.push(row.join(''));
  }

  // Conflicts
  if (sa.conflicts?.length){
    lines.push('');
    lines.push('Conflicts:');
    for (const c of sa.conflicts){
      lines.push(`  [${(c.severity || 'conflict').toUpperCase()}] ${c.field}: ${c.description}`);
    }
  }

  // Evidence hashes
  if (sa.source_hashes && Object.keys(sa.source_hashes).length){
    lines.push('');
    lines.push('Evidence SHA-256 fingerprints:');
    for (const [src, hash] of Object.entries(sa.source_hashes)){
      lines.push(`  ${src.padEnd(14)} ${hash}`);
    }
  }

  lines.push('');
  lines.push('Advisory: Source authority scores are engineering provenance metadata, not regulatory findings.');
  return lines.join('\n');
}

function fmt(v, d = 2){
  if (v === null || v === undefined || Number.isNaN(v)) return '—';
  return Number(v).toFixed(d);
}
