// Narrative generator.
//
// Renders the human-readable engineering exhibit from the structured
// genoa.exhibit.v2 object.  This is intentionally template-based and
// AI-FREE.  An AI assistant may *summarize* this output (and may, in
// the future, draft prose around it) but the source of truth is and
// remains the structured exhibit.  AI MUST NEVER:
//   - calculate contours
//   - change engineering outputs
//   - override warnings
//   - hide uncertainty
//   - fabricate measurements
//   - claim FCC approval

export const CERTIFICATION_LANGUAGE =
  'This exhibit was generated by Genoa FCC Propagation Studio. Deterministic FCC contour calculations are intended for review and certification by a qualified broadcast engineer prior to filing.';

export function renderNarrative(exhibit){
  const s   = exhibit.station_inputs || {};
  const m   = exhibit.calculation_method || {};
  const ip  = exhibit.interpolation || {};
  const rt  = exhibit.radial_table || [];
  const fr  = exhibit.filing_readiness || {};
  const ev  = exhibit.evidence || {};
  const pop = exhibit.population_estimate || {};
  const v   = exhibit.validation || {};

  const sections = {
    summary:             section_summary(exhibit),
    station_inputs:      section_inputs(s),
    fcc_method:          section_method(m, ip),
    contour_results:     section_contour_results(exhibit),
    radial_table:        section_radial_summary(rt, exhibit.contour_definitions || []),
    methodology:         section_methodology(exhibit),
    terrain_evidence:    section_terrain(ev),
    measurement_evidence:section_measurement(ev),
    population:          section_population(pop),
    warnings:            section_warnings(exhibit.warnings || [], fr),
    certification:       section_certification(fr)
  };

  const text = [
    sections.summary, sections.station_inputs, sections.fcc_method,
    sections.contour_results, sections.radial_table, sections.methodology,
    sections.terrain_evidence, sections.measurement_evidence,
    sections.population, sections.warnings, sections.certification
  ].join('\n\n');

  return { text, sections, certification_language: CERTIFICATION_LANGUAGE, ai_used: false };
}

const hr = title => `── ${title.toUpperCase()} ${'─'.repeat(Math.max(2, 60 - title.length))}`;

function section_summary(x){
  const s = x.station_inputs || {};
  const fr = x.filing_readiness || {};
  return [
    hr('Engineering Exhibit Summary'),
    `Station ${s.call || '—'} (facility ${s.facility_id || '—'})`,
    `Service: ${s.service || '—'}${s.fcc_class ? ' class ' + s.fcc_class : ''}`,
    `Generated: ${x.generated_at}`,
    `Filing readiness: ${fr.score ?? '—'}/100 — status ${fr.status || '—'}`
  ].join('\n');
}

function section_inputs(s){
  return [
    hr('Station / Facility Inputs'),
    `Frequency:       ${fmt(s.frequency)} ${s.frequency_unit || ''}`,
    `ERP (h):         ${fmt(s.erp_kw)} kW`,
    `HAAT (input):    ${s.service === 'AM' ? 'n/a (AM)' : fmt(s.haat_m_input) + ' m'}`,
    `Coordinates:     ${fmt(s.lat, 5)}, ${fmt(s.lon, 5)}`,
    `Pattern:         ${Array.isArray(s.pattern) ? `directional (${s.pattern.length} points)` : 'non-directional'}`,
    `Radial step:     ${s.radial_step_deg}°`,
    s.service === 'AM' ? `Ground σ:        ${fmt(s.ground_sigma_mS_m)} mS/m` : null
  ].filter(Boolean).join('\n');
}

function section_method(m, ip){
  return [
    hr('Applicable FCC Method'),
    `Method:          ${m.name || '—'}`,
    `Regulations:     ${(m.regulations || []).join(', ') || '—'}`,
    `Engine module:   ${m.engine_module || '—'}`,
    `Engine version:  ${m.engine_version || '—'}`,
    `Interpolation:`,
    `  along field:   ${ip?.along_field || '—'}`,
    `  along HAAT:    ${ip?.along_haat  || '—'}`,
    `  source:        ${ip?.source      || '—'}`
  ].join('\n');
}

function section_contour_results(x){
  const polygons = x.polygons || [];
  const lines = [hr('Contour Results')];
  for (const p of polygons){
    const fs = p.field_strength || {};
    lines.push(`${(p.label || p.contour_id).padEnd(36)} mean radial = ${fmt(p.mean_radial_km, 2)} km · area ≈ ${fmt(p.area_km2, 0)} km² (${fs.value ?? '—'} ${fs.unit ?? ''})`);
  }
  if (polygons.length === 0) lines.push('No contour polygons computed (engine returned an empty radial table).');
  return lines.join('\n');
}

function section_radial_summary(rt, contours){
  if (!rt.length) return hr('Radial Table Summary') + '\nradial table is empty.';
  const head = [hr('Radial Table Summary')];
  head.push(`Total radials:      ${rt.length}`);
  if (rt.length){
    const az0  = rt[0].azimuth_deg;
    const azN  = rt[rt.length-1].azimuth_deg;
    head.push(`Azimuth coverage:   ${az0}° … ${azN}°`);
  }
  head.push('Per-contour mean radial:');
  for (const c of contours){
    const ds = rt.map(r => r.contour_distances_km?.[c.id]).filter(Number.isFinite);
    if (!ds.length){ head.push(`  ${c.label.padEnd(34)} —`); continue; }
    const mean = ds.reduce((a,b)=>a+b,0)/ds.length;
    const min  = Math.min(...ds), max = Math.max(...ds);
    head.push(`  ${c.label.padEnd(34)} mean ${fmt(mean,2)} km  min ${fmt(min,2)} max ${fmt(max,2)}`);
  }
  return head.join('\n');
}

function section_methodology(x){
  const mv = x.method_versions || {};
  const sw = x.software_versions || {};
  const cd = mv.curve_dataset || {};
  return [
    hr('Methodology and Reproducibility'),
    `Genoa engine:    ${sw.genoa_engine}`,
    `Schema:          ${sw.schema}`,
    `Node:            ${sw.node}`,
    `Curve dataset:   ${cd.curve_version || '—'}  (meta sha256 ${(cd.meta_sha256 || '').slice(0,12)}…)`,
    `Curve files:`,
    ...Object.entries(cd.dataset_sha256 || {}).map(([k,h]) => `  · ${k.padEnd(18)} sha256 ${h.slice(0,12)}…`),
    `Reproducibility statement:`,
    `  This exhibit is a deterministic function of (station inputs, terrain HAAT per radial,`,
    `  curve dataset version, engine version). Re-running with the same inputs and the same`,
    `  curve dataset version on a different machine MUST produce the same radial table.`
  ].join('\n');
}

function section_terrain(ev){
  if (!ev?.terrain?.available){
    return hr('Supplemental Terrain / ITM Evidence') + '\nNo terrain evidence attached. Engine ran with flat HAAT (or n/a for AM).';
  }
  const t = ev.terrain;
  const lines = [hr('Supplemental Terrain / ITM Evidence')];
  lines.push(`Source:           ${t.source || '—'}`);
  lines.push(`Profiles:         ${t.profiles?.length || 0} radials`);
  return lines.join('\n');
}

function section_measurement(ev){
  if (!ev?.measurements?.available){
    return hr('Measurement Evidence') + '\nNo SDR / SigMF measurement records are attached. Field measurements are evidence, not authority.';
  }
  const m = ev.measurements;
  return [
    hr('Measurement Evidence'),
    `Source:           ${m.source || '—'}`,
    `Records:          ${m.n_records ?? m.records?.length ?? 0}`,
    `Calibrated:       ${m.calibrated ? 'yes' : 'no — measurements reported as raw indications'}`,
    `Author:           ${m.author || '—'}`,
    `Hardware:         ${m.hw || '—'}`
  ].join('\n');
}

function section_population(pop){
  return [
    hr('Population Estimate Disclaimer'),
    `Primary contour:  ~${(pop?.primary ?? 0).toLocaleString()} (${pop?.model || '—'})`,
    `Protected:        ~${(pop?.protected ?? 0).toLocaleString()}`,
    `THIS IS A PLACEHOLDER. A Census/ACS dispatch is required for any filing-grade population claim.`
  ].join('\n');
}

function section_warnings(warnings, fr){
  const lines = [hr('Warnings and Limitations')];
  if (!warnings.length) lines.push('No structured warnings raised.');
  for (const w of warnings){
    lines.push(`[${w.severity?.toUpperCase()}] ${w.code}  — ${w.title}`);
    if (w.detail) lines.push(`    ${w.detail}`);
  }
  if (fr?.blockers?.length){
    lines.push('');
    lines.push('Filing-readiness blockers:');
    for (const b of fr.blockers) lines.push(`  · ${b.code} — ${b.detail || b.description || ''}`);
  }
  if (fr?.recommendations?.length){
    lines.push('');
    lines.push('Recommendations:');
    for (const r of fr.recommendations) lines.push(`  · ${r}`);
  }
  return lines.join('\n');
}

function section_certification(fr){
  return [
    hr('Engineering Certification Placeholder'),
    CERTIFICATION_LANGUAGE,
    '',
    `Genoa filing readiness:   ${fr.score ?? '—'}/100  (${fr.status || '—'})`,
    `Engineer of record:       ___________________________`,
    `License #:                ___________________________`,
    `Date:                     ___________________________`,
    `Signature:                ___________________________`
  ].join('\n');
}

function fmt(v, d = 2){
  if (v === null || v === undefined || Number.isNaN(v)) return '—';
  return Number(v).toFixed(d);
}
