// Certification block — Genoa boilerplate + signature fields.
//
// Genoa never certifies an FCC filing.  The qualified broadcast engineer of
// record is the certifying party.  The boilerplate paragraph below is the
// only language Genoa attaches; signature fields are left blank for the
// engineer to complete.

export function buildCertificationSection(exhibit, options){
  const opt = options || {};
  const eng = opt.engineer_of_record || exhibit.station_inputs?.engineer_of_record || {};

  const boilerplate =
    'This exhibit was generated by Genoa FCC Propagation Studio.  ' +
    'Genoa provides deterministic technical calculations and supporting evidence.  ' +
    'Final certification remains the responsibility of the reviewing qualified broadcast engineer.';

  return {
    id:      'certification',
    type:    'certification',
    heading: 'CERTIFICATION',
    boilerplate,
    fields: [
      ['Engineer of Record',        eng.name        || ''],
      ['License / Certification',   eng.license     || ''],
      ['Firm',                      eng.firm        || ''],
      ['Date',                      eng.date        || ''],
      ['Signature',                 '']
    ]
  };
}
