// Certification block.  Two modes:
//
//   1. UNSEALED — Genoa boilerplate + blank fields for the engineer to
//      complete by hand.  Used when no PE has stamped the exhibit yet.
//
//   2. SEALED — exhibit.pe_certification is present (set by POST
//      /api/exhibits/certify).  Renders the PE name / license / state /
//      firm, the date, the signature ID, and the exhibit SHA-256 the
//      engineer signed.  This is the form that ships with FCC filings.
//
// Genoa never auto-certifies; the SEALED form only appears once a PE
// has stamped it via the workbench (or a direct API call with their
// engineer payload).

export function buildCertificationSection(exhibit, options){
  const opt = options || {};
  const cert = exhibit?.pe_certification;

  if (cert && cert.certified === true){
    const eng = cert.engineer || {};
    const expiry = eng.license_expiration ? `  (expires ${eng.license_expiration})` : '';
    return {
      id:           'certification',
      type:         'certification',
      heading:      'PROFESSIONAL ENGINEER CERTIFICATION',
      sealed:       true,
      statement:    eng.statement || '',
      fields: [
        ['Engineer of Record',        eng.name || ''],
        ['Title',                     eng.title || 'Professional Engineer'],
        ['License No.',               `${eng.license_no || ''}${eng.license_state ? ' (' + eng.license_state + ')' : ''}${expiry}`],
        ['Firm',                      eng.firm || '—'],
        ['Date Signed (UTC)',         cert.signed_at || ''],
        ['Signature ID',              cert.signature_id || ''],
        ['Exhibit SHA-256',           cert.exhibit_sha256 || ''],
        ['Hash Scope',                cert.hash_scope || ''],
        ['Software',                  `${cert.software || 'Genoa FCC Propagation Studio'} v${cert.software_version || ''}`]
      ],
      footer:
        'This exhibit is sealed.  Verify the seal by re-running the canonical-JSON ' +
        'SHA-256 over the exhibit (excluding the pe_certification block) and ' +
        'comparing to the stored hash above.  POST the exhibit to ' +
        '/api/exhibits/verify-cert for an automated check.'
    };
  }

  // Fallback: Genoa boilerplate + blank engineer-of-record fields.
  const eng = opt.engineer_of_record || exhibit?.station_inputs?.engineer_of_record || {};
  const boilerplate =
    'This exhibit was generated by Genoa FCC Propagation Studio.  ' +
    'Genoa provides deterministic technical calculations and supporting evidence.  ' +
    'Final certification remains the responsibility of the reviewing qualified broadcast engineer.';
  return {
    id:      'certification',
    type:    'certification',
    heading: 'CERTIFICATION',
    sealed:  false,
    boilerplate,
    fields: [
      ['Engineer of Record',        eng.name        || ''],
      ['License / Certification',   eng.license     || ''],
      ['Firm',                      eng.firm        || ''],
      ['Date',                      eng.date        || ''],
      ['Signature',                 '']
    ]
  };
}
