// Cover page — title + identification block.
//
// Conservative consulting-grade phrasing.  No marketing language.

export function buildCoverSection(exhibit){
  const s = exhibit.station_inputs || {};
  const mv = exhibit.method_versions || {};
  const fm = exhibit.facility_metadata || {};
  const lic = exhibit.evidence?.fcc_lms?.license || {};
  const fmt = (v, dash = '—') => (v === null || v === undefined || v === '') ? dash : String(v);
  const channel = s.service === 'AM'
    ? null
    : (Number.isFinite(Number(s.frequency)) ? Math.round((Number(s.frequency) - 87.9) / 0.2 + 200) : null);
  // Multi-source fallback for cover-page identity rows.  Operator
  // typically types facility_id + call + frequency + coords; the rest
  // is enriched downstream from FCC FMQ / FCC LMS / facility_metadata.
  // Reach into every shape these upstreams have used across vintages
  // (snake_case, camelCase, raw row vs license sub-object) so a
  // complete record displays even when station_inputs is sparse.
  const fmRaw = exhibit.facility_metadata?.raw || {};
  const lmsRaw = exhibit.evidence?.fcc_lms?.raw || {};
  const community = s.community || s.city || s.licensing_community
                 || s.community_of_license
                 || lic.community || lic.community_of_license || lic.city
                 || lic.licensing_community
                 || fm.community || fm.community_of_license || fm.city
                 || fmRaw.community || fmRaw.community_of_license || fmRaw.city || fmRaw.licensing_community
                 || lmsRaw.community || lmsRaw.community_of_license || lmsRaw.city;
  const fccClass  = s.fcc_class || s.class || s.station_class
                 || lic.fcc_class || lic.station_class || lic.class
                 || fm.fcc_class || fm.station_class || fm.class
                 || fmRaw.fcc_class || fmRaw.station_class || fmRaw.class
                 || lmsRaw.fcc_class || lmsRaw.station_class || lmsRaw.class;
  return {
    id:      'cover',
    type:    'cover',
    heading: 'ENGINEERING STATEMENT',
    rows: [
      ['Station',              fmt(s.call)],
      ['Facility ID',          fmt(s.facility_id)],
      channel != null ? ['Channel', String(channel)] : null,
      ['Frequency',            `${fmt(s.frequency)} ${fmt(s.frequency_unit)}`],
      ['Community of License', fmt(community)],
      ['Service',              fmt(s.service)],
      ['Class',                fmt(fccClass)],
      ['Prepared by',          fmt(exhibit.prepared_by || s.licensee || 'Engineer of Record')],
      ['Generated by',         'Genoa FCC Propagation Studio'],
      ['Engine Version',       fmt(mv.engine_version || mv.curve_engine || 'genoa-2.0')],
      ['Engine SHA',           fmt(mv.engine_sha || mv.dataset_meta_sha256?.slice(0, 12) || mv.fcc_orchestration?.commit?.slice(0, 12))],
      // Curve dataset: prefer the explicit `dataset` label set by the engine.
      // Fall back to the curve-dataset's own metadata (vendored tvfm_curves.js
      // for FM/TV, gwave.js for AM), or the dataset SHA-256 as a last resort
      // identifier so the row never shows just "—".
      ['Curve dataset',        fmt(mv.dataset
                                || mv.curve_dataset?.label
                                || mv.curve_dataset?.name
                                || (mv.curve_engine === 'fcc-canonical' ? 'FCC tvfm_curves.js (vendored, fcc/contours-api-node)' : null)
                                || (mv.curve_dataset?.meta_sha256 ? `dataset SHA-256 ${String(mv.curve_dataset.meta_sha256).slice(0, 12)}…` : null)
                                || (mv.dataset_meta_sha256 ? `dataset SHA-256 ${String(mv.dataset_meta_sha256).slice(0, 12)}…` : null))],
      ['Date',                 new Date().toISOString().slice(0, 10)]
    ].filter(Boolean)
  };
}
