// Cover page — title + identification block.
//
// Conservative consulting-grade phrasing.  No marketing language.

import { resolveCommunity, resolveClass } from './_identity.js';

export function buildCoverSection(exhibit){
  const s = exhibit.station_inputs || {};
  const mv = exhibit.method_versions || {};
  const sig = exhibit.engine_signature || {};
  const fmt = (v, dash = '—') => (v === null || v === undefined || v === '') ? dash : String(v);
  const channel = s.service === 'AM'
    ? null
    : (Number.isFinite(Number(s.frequency)) ? Math.round((Number(s.frequency) - 87.9) / 0.2 + 200) : null);
  // Identity fields (community-of-license, station class) walk a
  // multi-source fallback chain — operator-typed station_inputs may be
  // sparse and the canonical values often live in evidence.fcc_lms.*
  // or facility_metadata.raw.  Shared with executiveSummary.js so the
  // two sections never disagree (KAZM regression class).
  const community = resolveCommunity(exhibit);
  const fccClass  = resolveClass(exhibit);
  return {
    id:      'cover',
    type:    'cover',
    heading: 'ENGINEERING STATEMENT',
    rows: [
      ['Station',              fmt(s.call)],
      ['Facility ID',          fmt(s.facility_id)],
      channel != null ? ['Channel', String(channel)] : null,
      ['Frequency',            `${fmt(s.frequency)} ${fmt(s.frequency_unit)}`],
      ['Community of License', fmt(community)],
      ['Service',              fmt(s.service)],
      ['Class',                fmt(fccClass)],
      ['Prepared by',          fmt(exhibit.prepared_by || s.licensee || 'Engineer of Record')],
      ['Generated by',         'Genoa FCC Propagation Studio'],
      ['Engine Version',       fmt(sig.version || mv.engine_version || mv.curve_engine || 'genoa-2.0')],
      // Engine SHA = the Genoa engine's own git commit, NOT the FCC
      // orchestration commit (which is the upstream contours-api-node
      // repo).  Mis-pointing this at fcc_orchestration.commit would
      // falsely identify the deployed Genoa engine by its FCC upstream
      // and make exhibit-to-engine attestation untraceable.  Render
      // em-dash when no genoa-engine sig.hash / mv.engine_sha is
      // available — never silently substitute mv.fcc_orchestration.commit.
      ['Engine SHA',           fmt((sig.hash || mv.engine_sha)?.slice?.(0, 12))],
      // Curve dataset: prefer the explicit `dataset` label set by the engine.
      // AM exhibits stamp curve_dataset.curve_version (e.g.
      // "fcc-contours-api-node@b55870d3f2") and curve_dataset.dataset_sha256
      // (a per-file SHA-256 object for gwave.js + gwave_field.json), not the
      // FM-style `meta_sha256` scalar.  FM/TV use the older curve_engine
      // "fcc-canonical" string.  Fall through every shape so the row never
      // shows "—" on a real exhibit.
      ['Curve dataset',        fmt(mv.dataset
                                || mv.curve_dataset?.label
                                || mv.curve_dataset?.name
                                || mv.curve_dataset?.curve_version
                                || (mv.curve_engine === 'fcc-canonical' ? 'FCC tvfm_curves.js (vendored, fcc/contours-api-node)' : null)
                                || (mv.curve_dataset?.meta_sha256 ? `dataset SHA-256 ${String(mv.curve_dataset.meta_sha256).slice(0, 12)}…` : null)
                                || (mv.dataset_meta_sha256 ? `dataset SHA-256 ${String(mv.dataset_meta_sha256).slice(0, 12)}…` : null)
                                || (mv.curve_dataset?.dataset_sha256 && typeof mv.curve_dataset.dataset_sha256 === 'object'
                                      ? `dataset SHA-256 ${String(Object.values(mv.curve_dataset.dataset_sha256)[0] || '').slice(0, 12)}…`
                                      : null))],
      ['Date',                 new Date().toISOString().slice(0, 10)]
    ].filter(Boolean)
  };
}
