// Cover page — title + identification block.
//
// Conservative consulting-grade phrasing.  No marketing language.

export function buildCoverSection(exhibit){
  const s = exhibit.station_inputs || {};
  const mv = exhibit.method_versions || {};
  const fmt = (v, dash = '—') => (v === null || v === undefined || v === '') ? dash : String(v);
  const channel = s.service === 'AM'
    ? null
    : (Number.isFinite(Number(s.frequency)) ? Math.round((Number(s.frequency) - 87.9) / 0.2 + 200) : null);
  return {
    id:      'cover',
    type:    'cover',
    heading: 'ENGINEERING STATEMENT',
    rows: [
      ['Station',              fmt(s.call)],
      ['Facility ID',          fmt(s.facility_id)],
      channel != null ? ['Channel', String(channel)] : null,
      ['Frequency',            `${fmt(s.frequency)} ${fmt(s.frequency_unit)}`],
      ['Community of License', fmt(s.community || s.city || s.licensing_community)],
      ['Service',              fmt(s.service)],
      ['Class',                fmt(s.fcc_class)],
      ['Prepared by',          fmt(exhibit.prepared_by || s.licensee || 'Engineer of Record')],
      ['Generated by',         'Genoa FCC Propagation Studio'],
      ['Engine Version',       fmt(mv.engine_version || mv.curve_engine || 'genoa-2.0')],
      ['Engine SHA',           fmt(mv.engine_sha || mv.dataset_meta_sha256?.slice(0, 12) || mv.fcc_orchestration?.commit?.slice(0, 12))],
      ['Curve dataset',        fmt(mv.dataset)],
      ['Date',                 new Date().toISOString().slice(0, 10)]
    ].filter(Boolean)
  };
}
